version: "3.9"

volumes:
  db-volume:

networks:
  application:
    driver: bridge

services:
  nginx:
    build:
        context: ./dockerfile/nginx/
        dockerfile: Dockerfile
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - spring-boot
    networks:
      - application

  spring-boot:
    container_name: spring-boot
    build:
      context: .
      dockerfile: dockerfile/web/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE: db
    depends_on:
      - db
    networks:
      - application
    deploy:
      replicas: 1
      restart_policy: 
        condition: on-failure
      update_config:
        delay: 5s

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cursinho
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      - application
    ports:
      - "5432:5432"
