server.port: 8081

# SETUP H2 CONFIGURATION
spring:
  web.locale: pt_BR

  # H2 PATH
  h2:
    console:
      enabled: true
      
  # DATASOURCE CONNECTION PROPERTIES
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=LEGACY;
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialization-mode: always  # Esta linha garante que o Spring Boot execute scripts de inicialização automaticamente
    schema: classpath:schema.sql
    data: classpath:data.sql

  jpa:
    # HIBERNATE CONFIGURATION YAML
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      jpa.show-sql: true
      format_sql: true
      default_schema: dbo

